name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install fastapi uvicorn loguru sqlite3 sqlalchemy prometheus_client jwt

      - name: Run Tests
        run: pytest tests/

      - name: Build and Push Docker Image
        run: docker build -t my-claim-api .
