name: CI/CD Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to cloud
        run: echo "Deploying..."
